const DATE_FORMAT = "MMMM yyyy";
const DATE_FORMAT_WITH_DAY = "dd-MMM-yyyy";

const MAX_TEXTAREA_INPUT = 1000;
const MAX_TEXT_INPUT = 200;

const PAGE_PATHS = {
  PROFILE: "/",
};

export { DATE_FORMAT, DATE_FORMAT_WITH_DAY, MAX_TEXTAREA_INPUT, MAX_TEXT_INPUT, PAGE_PATHS };
